---
# tasks file for ansible-telegraf

- name: "Install on RedHat"
  include_tasks: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat" and not telegraf_agent_docker

- name: "Install on Debian"
  include_tasks: "Debian.yml"
  when:
    - ansible_os_family == "Debian" and not telegraf_agent_docker
  tags:
    - telegraf
    - packages

- name: "Install on Archlinux"
  include_tasks: "Archlinux.yml"
  when:
    - ansible_os_family == "Archlinux" and not telegraf_agent_docker

- name: "Install on Suse"
  include_tasks: "Suse.yml"
  when: ansible_os_family == "Suse" and not telegraf_agent_docker

- name: "Install on FreeBSD"
  include_tasks: "FreeBSD.yml"
  when:
    - ansible_os_family == "FreeBSD" and not telegraf_agent_docker

- name: "Install on MacOS"
  include_tasks: "MacOS.yml"
  when:
    - ansible_os_family == "Darwin" and not telegraf_agent_docker

- include_tasks: "{{ item }}"
  # Only parse docker.yml if it's going to be used:
  loop: "{{ [ 'docker.yml' ] if telegraf_agent_docker else [] }}"

- name: "Configure Telegraf"
  include_tasks: "configure_linux.yml"
  when:
    - ansible_os_family not in ['Windows', 'Darwin']

- name: "Install / Configure telegraf on Windows"
  include_tasks: "{{ item }}"
  # Only parse configure_windows.yml if it's going to be used:
  loop: '{{ [ "configure_windows.yml" ] if ansible_os_family == "Windows" and not telegraf_agent_docker else [] }}'

- name: "Install / Configure telegraf on MacOS"
  include_tasks: "configure_macos.yml"
  when:
    - ansible_os_family == "Darwin" and not telegraf_agent_docker
