- name: Granting telegraf account sudo priviliges
  ansible.builtin.template:
    src: telegraf_sudoers.j2
    dest: /etc/sudoers.d/telegraf
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s

- name: Remove unwanted file
  ansible.builtin.file:
    path: /etc/sudoers.d/MONITORING
    state: absent
  notify:
    - Restart Telegraf
