---
# handlers file for ansible-telegraf
- name: "Restart Telegraf container"
  docker_container:
    name: "{{ telegraf_agent_docker_name }}"
    restart: True
  when: telegraf_agent_docker
  ignore_errors: "{{ ansible_check_mode }}"
